### ISSUE TITLE
ldap集成

### ISSUE THREAD

**Issue by lkun** [dianrong/UniAuth#4]
是否可以支持ldap集成？是否预留有接入ldap的扩展点？

**Comment by Agileaq** [comment]
哈哈， 我们内网目前正在开发ldap 的authentication.   开发好之后会推上来。

**Comment by Agileaq** [comment]
CAS本身支持多个数据源做authentication的，  所以你也可以自己开一个branch来做。

**Comment by lkun** [comment]
是的，我也有这个打算，就想问问作者，因为看了源码，关于接入ldap，该在他们现有的源码基础上哪个地方入手比较合适 ，@Agileaq  想问下你是从哪个地方入手呢？

**Comment by houfeichj** [comment]
@lkun 如果只是接入ldap的话,可以考虑到uniauth-server中去做. login和getUserDetailInfo这两个接口是登陆的时候会用到的. 这两个接口的数据从ldap中来就能满足需求吧.

**Comment by lkun** [comment]
了解了 谢谢  @houfeichj

**Comment by Agileaq** [comment]
@lkun  没有问题的话，我把这个issue关闭了哦。  入手的点从我的角度有两个地方：
1. project CAS (CAS官方的提供插件的方式的做法)
2. project uniauth (hjoufeichj 建议的做法)
