### ISSUE TITLE
数据级权限控制

### ISSUE THREAD

**Issue by wangshengwangsheng** [dianrong/UniAuth#5]
请问如何进行数据级别的权限控制。比如一个部门的负责人能看到自己部门以及下级部门的员工的数据，而不能看到其他平级部门以及上级部门员工的数据。

**Comment by houfeichj** [comment]
@wangshengwangsheng  目前uniauth还没有提供完整的数据权限控制机制。 你可以尝试通过自定义privilege权限，然后自己做控制。

**Comment by Agileaq** [comment]
@wangshengwangsheng  参考techops的实现， 不同的人 访问相同的api, 能够访问的数据严格受到限制。 比如 TechOpsPermissionEvaluator 类里面自定义了很多hasPermission的权限， 
具体的应用看 TagAction 这个类里面的query参数， principal.domainIdSet.contains(#tagQuery.domainId)) 你作为一般管理不能查询 别的系统的tag
